### ISSUE TITLE
Wrong URL for more information in the repository settings.

### ISSUE THREAD

**Issue by bentolor** [PombeirP/ReSharper.AutoFormatOnSave#11]
The repository mentions http://www.developerintheflow.blogspot.ch/2012/10/keeping-code-formatted-easy-way.html as documentation. This leads to a 404.

Probably the right link is http://blog.pedropombeiro.com/keeping-code-formatted-the-easy-way/

**Comment by PombeirP** [comment]
Fixed. Thanks for pointing it out!
