### ISSUE TITLE
Does not install on Visual Studio 2015

### ISSUE THREAD

**Issue by alarkvell** [PombeirP/ReSharper.AutoFormatOnSave#16]
ReSharper.AutoFormatOnSave.vsix version 1.2.2 does not offer the option to install on Visual Studio 2015.

**Comment by PombeirP** [comment]
Thanks for reporting. Should be fixed with version 1.2.3.

**Comment by alarkvell** [comment]
Thank you for quick response. Version 1.2.3 installs on Visual Studio 2015 successfully.
