### ISSUE TITLE
ReSharper 2016.1 - incompatible?!

### ISSUE THREAD

**Issue by yudansha** [PombeirP/ReSharper.AutoFormatOnSave#20]
Installed the new version of ReSharper (2016.1) and tried to use the plugin but nothing happens.
At the moment I am using VS 2013.
Could it be that this plugin is not compatible with the new version of ReSharper?

**Comment by feitzi** [comment]
same problem with VS 2015 and R# 2016.01

**Comment by evilbaschdi** [comment]
ReSharper_SilentCleanupCode has to be changed to ReSharper.ReSharper_SilentCleanupCode
...that's all

**Comment by monkey-dsc** [comment]
where do you do this changes? (ReSharper_SilentCleanupCode)

**Comment by evilbaschdi** [comment]
ReSharper.AutoFormatOnSavePackage.cs line 47

**Comment by monkey-dsc** [comment]
oh okay i haven't viewd the source code yet, just installed the extension

**Comment by Nargzul** [comment]
I just issued a pull request( #21 ) that solved the issue with Resharper 2016.1 and is still compatible with the previous versions

**Comment by pato-p** [comment]
@PombeirP: Any update on this?

**Comment by PombeirP** [comment]
The new 1.2.4 version should fix it.

**Comment by pato-p** [comment]
It works for me, thanks!
