### ISSUE TITLE
Extension is failed to load

### ISSUE THREAD

**Issue by andrewmolyuk** [PombeirP/ReSharper.AutoFormatOnSave#7]
After upgrade to 1.2.0 I've started to fail.

Environment : Windows 7 x64, VS2012 Pro U4, Resharper 7.1.1
Activity log extraction:

324  Begin package load [ReSharper.AutoFormatOnSave.ReSharper_AutoFormatOnSavePackage, ReSharper.AutoFormatOnSave, Version=1.2.0.0, Culture=neutral, PublicKeyToken=0c13295e2103ff99] {2C65FBA8-3ECB-4004-8EE3-6D9E62CD987A}  VisualStudio 2013/11/27 13:29:22.246 

325 ERROR CreateInstance failed for package [ReSharper.AutoFormatOnSave.ReSharper_AutoFormatOnSavePackage, ReSharper.AutoFormatOnSave, Version=1.2.0.0, Culture=neutral, PublicKeyToken=0c13295e2103ff99] {2C65FBA8-3ECB-4004-8EE3-6D9E62CD987A} 80070002 VisualStudio 2013/11/27 13:29:22.252 

326 ERROR End package load [ReSharper.AutoFormatOnSave.ReSharper_AutoFormatOnSavePackage, ReSharper.AutoFormatOnSave, Version=1.2.0.0, Culture=neutral, PublicKeyToken=0c13295e2103ff99] {2C65FBA8-3ECB-4004-8EE3-6D9E62CD987A} 80004005 - E_FAIL VisualStudio 2013/11/27 13:29:22.253 

![image](https://f.cloud.github.com/assets/3962313/1631618/32dedb0e-5769-11e3-83bd-b586a94ea82d.png)

**Comment by chwt** [comment]
Same environment and error as @taconaut.

Just copying the first search engine link on that topic:
http://stackoverflow.com/questions/25606632/how-can-a-vs-extension-target-multiple-versions-in-regard-to-microsoft-visualstu

**Comment by PombeirP** [comment]
Should be fixed with new version 1.2.2

**Comment by taconaut** [comment]
Thanks! I can confirm my issue is fixed with the new release.

**Comment by PombeirP** [comment]
Glad to hear that @taconaut! I apologize for the time it took to fix it, but I'm not using the extension myself at this point, so I didn't really have things set up to test it.
